import Navigation from "../../components/Navigation";
import Footer from "../../components/Footer";
import { Link } from "../../../lib/routing";
import { PRODUCT_HERO_IMAGES } from "../../../lib/imagery";

const content = {
  en: {
    title: "ASHSIM",
    subheading: "Ship Information Modelling Intelligence",
    tagline:
      "Connect your existing 3D design software to an AI analysis layer. Get clash detection, rule compliance checks, and structured build records without changing your workflow.",
    heroCtaPrimary: "Request early access",
    heroCtaSecondary: "See how it works",
    howTitle: "How it works",
    steps: [
      {
        title: "Export from your CAD software",
        body: "ASHSIM works with AVEVA Marine, ShipConstructor, and CADMATIC. Export your IFC or STEP file in one click.",
      },
      {
        title: "AI analysis in minutes",
        body: "Upload to ASHSIM and get an instant analysis: clash detection, IACS rule compliance, steel grade verification, and a prioritised issue list generated by AI.",
      },
      {
        title: "Structured digital record",
        body: "Every finding, drawing, and quality record stays in one place. When the vessel delivers, the complete build record transfers to the owner.",
      },
    ],
    featuresTitle: "What ASHSIM analyses",
    features: [
      {
        title: "IFC / BIM Model Analysis",
        desc: "Clash detection, IACS material grade checks, element completeness, and anomaly detection across your structural model.",
      },
      {
        title: "Technical Drawing Analysis",
        desc: "Upload PDFs and drawing exports. AI extracts dimensions, revision history, and compliance notes automatically.",
      },
      {
        title: "Construction Quality Records",
        desc: "Optional modules for block tracking, welding QC, NCR management, and milestone tracking as you need them.",
      },
    ],
    pricingTitle: "Simple, project-based pricing",
    tiers: [
      {
        name: "Trial",
        price: "Free for 30 days",
        items: [
          "1 project",
          "IFC upload and AI analysis",
          "Technical drawing analysis",
          "No credit card required",
        ],
      },
      {
        name: "Starter",
        price: "£999 / project / month",
        items: [
          "Up to 3 active projects",
          "IFC and drawing analysis",
          "Plugin export for AVEVA and ShipConstructor",
          "10 users",
        ],
      },
      {
        name: "Professional",
        price: "£2,499 / month",
        items: [
          "Up to 10 active projects",
          "All analysis features",
          "All optional modules: block tracking, welding QC, NCR, milestones, documents, handover package",
          "25 users",
          "Priority support",
        ],
      },
    ],
    pricingNote:
      "Enterprise pricing available for shipyard groups and class societies. Contact info@asheriv.com",
    earlyTitle: "Currently in early access",
    earlyBody:
      "ASHSIM is available to a limited number of shipyards for early access testing. If you are building vessels and want to pilot AI-powered model analysis, we would like to work with you.",
    earlyCta: "Apply for early access",
  },
  tr: {
    title: "ASHSIM",
    subheading: "Gemi Bilgi Modelleme Zekasi",
    tagline:
      "Mevcut 3B tasarim yaziliminizi bir AI analiz katmanina baglayin. Is akisinizi degistirmeden cakisma tespiti, kural uyumluluk kontrolleri ve yapilandirilmis insaat kayitlari alin.",
    heroCtaPrimary: "Erken erisim talep et",
    heroCtaSecondary: "Nasil calisir",
    howTitle: "Nasil calisir",
    steps: [
      {
        title: "CAD yaziliminizdan disa aktarin",
        body: "ASHSIM, AVEVA Marine, ShipConstructor ve CADMATIC ile calisir. IFC veya STEP dosyanizi tek tikla disa aktarin.",
      },
      {
        title: "Dakikalar icinde AI analizi",
        body: "ASHSIM'e yukleyin ve aninda analiz alin: cakisma tespiti, IACS kural uyumlulugu, celik sinifi dogrulama ve AI tarafindan olusturulan oncelikli sorun listesi.",
      },
      {
        title: "Yapilandirilmis dijital kayit",
        body: "Her bulgu, cizim ve kalite kaydi tek yerde kalir. Gemi teslim edildiginde, tam insaat kaydi armatore devredilir.",
      },
    ],
    featuresTitle: "ASHSIM ne analiz eder",
    features: [
      {
        title: "IFC / BIM Model Analizi",
        desc: "Yapisal modelinizde cakisma tespiti, IACS malzeme sinifi kontrolleri, eleman tamligi ve anomali tespiti.",
      },
      {
        title: "Teknik Resim Analizi",
        desc: "PDF ve cizim ciktilarini yukleyin. AI boyutlari, revizyon gecmisini ve uyumluluk notlarini otomatik cikarir.",
      },
      {
        title: "Insaat Kalite Kayitlari",
        desc: "Ihtiyaciniza gore blok takibi, kaynak QC, URT yonetimi ve kilometre tasi takibi icin istege bagli moduller.",
      },
    ],
    pricingTitle: "Basit, proje bazli fiyatlandirma",
    tiers: [
      {
        name: "Deneme",
        price: "30 gun ucretsiz",
        items: [
          "1 proje",
          "IFC yukleme ve AI analizi",
          "Teknik resim analizi",
          "Kredi karti gerekmez",
        ],
      },
      {
        name: "Starter",
        price: "£999 / proje / ay",
        items: [
          "3 aktif projeye kadar",
          "IFC ve resim analizi",
          "AVEVA ve ShipConstructor icin eklenti ciktisi",
          "10 kullanici",
        ],
      },
      {
        name: "Professional",
        price: "£2,499 / ay",
        items: [
          "10 aktif projeye kadar",
          "Tum analiz ozellikleri",
          "Tum istege bagli moduller: blok takibi, kaynak QC, URT, kilometre taslari, dokumanlar, teslim paketi",
          "25 kullanici",
          "Oncelikli destek",
        ],
      },
    ],
    pricingNote:
      "Tersane gruplari ve klas kuruluslari icin kurumsal fiyatlandirma mevcuttur. info@asheriv.com adresinden iletisime gecin",
    earlyTitle: "Su anda erken erisimde",
    earlyBody:
      "ASHSIM, sinirli sayida tersane icin erken erisim testine aciktir. Gemi insa ediyorsaniz ve AI destekli model analizini pilot olarak denemek istiyorsaniz, sizinle calismak isteriz.",
    earlyCta: "Erken erisim basvurusu",
  },
} as const;

export default async function AshsimPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  const c = content[locale as keyof typeof content] ?? content.en;

  return (
    <>
      <Navigation />
      <main id="main-content" className="min-h-screen bg-[#0A0F1E] text-white">
        <section
          className="relative border-b border-white/10 pt-32 pb-20 sm:pt-40"
          style={{
            backgroundImage: `linear-gradient(to bottom, rgba(10,15,30,0.85), rgba(10,15,30,0.92)), url(${PRODUCT_HERO_IMAGES.sim})`,
            backgroundSize: "cover",
            backgroundPosition: "center",
          }}
        >
          <div className="mx-auto max-w-7xl px-6 sm:px-10 lg:px-16">
            <h1 className="font-heading text-4xl font-bold sm:text-5xl lg:text-6xl">{c.title}</h1>
            <p className="mt-3 text-xl font-medium text-[#00D4FF] sm:text-2xl">{c.subheading}</p>
            <p className="mt-6 max-w-3xl text-lg leading-relaxed text-[#CBD5E1]">{c.tagline}</p>
            <div className="mt-8 flex flex-wrap gap-3">
              <Link
                href="/#contact"
                className="rounded-full bg-[#00D4FF] px-6 py-3 text-sm font-semibold text-[#0A0F1E] transition hover:bg-[#67E5FF]"
              >
                {c.heroCtaPrimary}
              </Link>
              <a
                href="#how-it-works"
                className="rounded-full bg-[#0A0F1E] px-6 py-3 text-sm font-semibold text-white ring-1 ring-white/25 transition hover:bg-[#1C3D5A]"
              >
                {c.heroCtaSecondary}
              </a>
            </div>
          </div>
        </section>

        <section
          id="how-it-works"
          className="scroll-mt-24 bg-[#F7F9FA] px-6 py-16 text-[#3D4852] sm:px-10 lg:px-16"
        >
          <div className="mx-auto max-w-7xl">
            <h2 className="text-center font-heading text-3xl font-bold text-[#0A0F1E]">{c.howTitle}</h2>
            <div className="mx-auto mt-10 grid max-w-5xl grid-cols-1 gap-6 md:grid-cols-3">
              {c.steps.map((step, index) => (
                <div key={step.title} className="rounded-xl border border-[#0A0F1E]/10 bg-white p-6 shadow-sm">
                  <div className="mb-4 flex h-10 w-10 items-center justify-center rounded-full bg-[#00D4FF]/15 text-sm font-bold text-[#0A0F1E]">
                    {index + 1}
                  </div>
                  <h3 className="text-lg font-semibold text-[#0A0F1E]">{step.title}</h3>
                  <p className="mt-3 text-sm leading-relaxed">{step.body}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="bg-[#0A0F1E] px-6 py-16 sm:px-10 lg:px-16">
          <div className="mx-auto max-w-7xl">
            <h2 className="text-center font-heading text-3xl font-bold text-white">{c.featuresTitle}</h2>
            <div className="mx-auto mt-10 grid max-w-5xl grid-cols-1 gap-6 md:grid-cols-3">
              {c.features.map((feature) => (
                <div
                  key={feature.title}
                  className="rounded-xl border border-white/10 bg-[#0D1627] p-6"
                >
                  <div className="mb-4 h-2 w-10 rounded-full bg-[#00D4FF]" />
                  <h3 className="mb-3 text-lg font-semibold text-white">{feature.title}</h3>
                  <p className="text-sm leading-relaxed text-[#CBD5E1]">{feature.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="bg-[#F7F9FA] px-6 py-16 text-[#3D4852] sm:px-10 lg:px-16">
          <div className="mx-auto max-w-7xl">
            <h2 className="text-center font-heading text-3xl font-bold text-[#0A0F1E]">{c.pricingTitle}</h2>
            <div className="mx-auto mt-10 grid max-w-5xl grid-cols-1 gap-6 md:grid-cols-3">
              {c.tiers.map((tier) => (
                <div
                  key={tier.name}
                  className="flex flex-col rounded-xl border border-[#0A0F1E]/10 bg-white p-6 shadow-sm"
                >
                  <h3 className="text-lg font-semibold text-[#0A0F1E]">{tier.name}</h3>
                  <p className="mt-2 text-xl font-bold text-[#00D4FF]">{tier.price}</p>
                  <ul className="mt-6 flex-1 space-y-3 text-sm leading-relaxed">
                    {tier.items.map((item) => (
                      <li key={item} className="flex gap-2">
                        <span className="mt-1 text-[#00D4FF]" aria-hidden>
                          •
                        </span>
                        <span>{item}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
            <p className="mx-auto mt-8 max-w-3xl text-center text-sm text-[#3D4852]">{c.pricingNote}</p>
          </div>
        </section>

        <section className="bg-[#0A0F1E] px-6 py-16 sm:px-10 lg:px-16">
          <div className="mx-auto max-w-4xl rounded-xl border border-white/10 bg-[#0D1627] p-8 text-center sm:p-10">
            <h2 className="text-2xl font-semibold text-white sm:text-3xl">{c.earlyTitle}</h2>
            <p className="mt-4 leading-relaxed text-[#CBD5E1]">{c.earlyBody}</p>
            <Link
              href="/#contact"
              className="mt-8 inline-block rounded-full bg-[#00D4FF] px-8 py-3 text-sm font-semibold text-[#0A0F1E] transition hover:bg-[#67E5FF]"
            >
              {c.earlyCta}
            </Link>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
